dependencies:
- name: anandkumarb
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: springboot-application-example
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: springboot-example
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
